k8s_config:
- manifest_path: manifests/prod
  cluster_info:
    cluster_id: "768c3954-c2ba-5260-9ef0-cf6ed4a9ac42"
    cluster_name: "Production"
#- manifest_path: manifests/test
  #cluster_info:
    #cluster_id: "12344455324"
    #cluster_name: "Staging"
