apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorMapping
metadata:
  name: quote
  namespace: ambassador
spec:
  hostname: "*"
  prefix: /quote/
  service: quote
---
apiVersion: v1
kind: Service
metadata:
  name: quote
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: quote
  type: ClusterIP
